# Generated by Django 2.0.5 on 2018-06-16 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180612_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='answer',
            field=models.TextField(verbose_name='Odpowiedź'),
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Adres email'),
        ),
        migrations.AlterField(
            model_name='form',
            name='forename',
            field=models.CharField(max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='form',
            name='phoneNumber',
            field=models.CharField(max_length=50, verbose_name='Numer telefonu'),
        ),
        migrations.AlterField(
            model_name='form',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Pytanie'),
        ),
    ]
